
package ClientPackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMathService", targetNamespace = "http://ServerPackage/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMathService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://ServerPackage/", className = "ClientPackage.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://ServerPackage/", className = "ClientPackage.SubtractResponse")
    @Action(input = "http://ServerPackage/IMathService/subtractRequest", output = "http://ServerPackage/IMathService/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ServerPackage/", className = "ClientPackage.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ServerPackage/", className = "ClientPackage.MultiplyResponse")
    @Action(input = "http://ServerPackage/IMathService/multiplyRequest", output = "http://ServerPackage/IMathService/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ServerPackage/", className = "ClientPackage.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ServerPackage/", className = "ClientPackage.AddResponse")
    @Action(input = "http://ServerPackage/IMathService/addRequest", output = "http://ServerPackage/IMathService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://ServerPackage/", className = "ClientPackage.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://ServerPackage/", className = "ClientPackage.DivideResponse")
    @Action(input = "http://ServerPackage/IMathService/divideRequest", output = "http://ServerPackage/IMathService/divideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
