
package ClientWSDL;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotFound", targetNamespace = "http://service/")
public class NotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotFound_Exception(String message, NotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotFound_Exception(String message, NotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ClientWSDL.NotFound
     */
    public NotFound getFaultInfo() {
        return faultInfo;
    }

}
