
package service1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceWeb1ImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/serviceweb1?wsdl")
public class HotelServiceWeb1ImplService
    extends Service
{

    private final static URL HOTELSERVICEWEB1IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSERVICEWEB1IMPLSERVICE_EXCEPTION;
    private final static QName HOTELSERVICEWEB1IMPLSERVICE_QNAME = new QName("http://service/", "HotelServiceWeb1ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/serviceweb1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICEWEB1IMPLSERVICE_WSDL_LOCATION = url;
        HOTELSERVICEWEB1IMPLSERVICE_EXCEPTION = e;
    }

    public HotelServiceWeb1ImplService() {
        super(__getWsdlLocation(), HOTELSERVICEWEB1IMPLSERVICE_QNAME);
    }

    public HotelServiceWeb1ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICEWEB1IMPLSERVICE_QNAME, features);
    }

    public HotelServiceWeb1ImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICEWEB1IMPLSERVICE_QNAME);
    }

    public HotelServiceWeb1ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICEWEB1IMPLSERVICE_QNAME, features);
    }

    public HotelServiceWeb1ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceWeb1ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHotelServiceWeb1
     */
    @WebEndpoint(name = "HotelServiceWeb1ImplPort")
    public IHotelServiceWeb1 getHotelServiceWeb1ImplPort() {
        return super.getPort(new QName("http://service/", "HotelServiceWeb1ImplPort"), IHotelServiceWeb1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHotelServiceWeb1
     */
    @WebEndpoint(name = "HotelServiceWeb1ImplPort")
    public IHotelServiceWeb1 getHotelServiceWeb1ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "HotelServiceWeb1ImplPort"), IHotelServiceWeb1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICEWEB1IMPLSERVICE_EXCEPTION!= null) {
            throw HOTELSERVICEWEB1IMPLSERVICE_EXCEPTION;
        }
        return HOTELSERVICEWEB1IMPLSERVICE_WSDL_LOCATION;
    }

}
