
package service1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelServiceWeb1", targetNamespace = "http://service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelServiceWeb1 {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns service1.Agence
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/agenceLoginRequest", output = "http://service/IHotelServiceWeb1/agenceLoginResponse")
    public Agence agenceLogin(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/getAgenceIdentifiantRequest", output = "http://service/IHotelServiceWeb1/getAgenceIdentifiantResponse")
    public String getAgenceIdentifiant(
        @WebParam(name = "arg0", partName = "arg0")
        Agence arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service1.ProposeArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/getAllCombinationsRequest", output = "http://service/IHotelServiceWeb1/getAllCombinationsResponse")
    public ProposeArray getAllCombinations(
        @WebParam(name = "arg0", partName = "arg0")
        Agence arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", partName = "arg2")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/getNombrePropseRequest", output = "http://service/IHotelServiceWeb1/getNombrePropseResponse")
    public int getNombrePropse(
        @WebParam(name = "arg0", partName = "arg0")
        Agence arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", partName = "arg2")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/prixChoisiRequest", output = "http://service/IHotelServiceWeb1/prixChoisiResponse")
    public double prixChoisi(
        @WebParam(name = "arg0", partName = "arg0")
        Propose arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Agence arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/getHotelNomRequest", output = "http://service/IHotelServiceWeb1/getHotelNomResponse")
    public String getHotelNom(
        @WebParam(name = "arg0", partName = "arg0")
        Propose arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/downloadImageRequest", output = "http://service/IHotelServiceWeb1/downloadImageResponse")
    public byte[] downloadImage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service1.HotelPartenaireTarifArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service/IHotelServiceWeb1/getAgencePartenaireRequest", output = "http://service/IHotelServiceWeb1/getAgencePartenaireResponse")
    public HotelPartenaireTarifArray getAgencePartenaire(
        @WebParam(name = "arg0", partName = "arg0")
        Agence arg0);

}
